config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'countdown#game'

  get 'score', to: 'countdown#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countdown_controller.rb
require "open-uri"
require "json"

class CountdownController < ApplicationController
  def game
    @grid = generate_grid(9)
  end

  def score
    @attempt = params[:word]
    @time = Time.now.to_i - params[:start_time].to_i
    @my_grid = params[:my_grid]
    @score = score_and_message(@attempt, @my_grid, @time)
  end

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a.sample }
  end

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countdown_helper.rb
module CountdownHelper
end

app/views/countdown/game.html.erb
<h2>Here is your grid</h2>
<h2><%= @grid.join(" ") %></h2>


<form action="score">
  <label for="question">What's your best shot ?</label>
  <input type="text" id="question" name="word" placeholder="Anticonstitutionnellement">
  <input type="hidden" id="start_time" name="start_time" value="<%= Time.now.to_i %>">
  <input type="hidden" id="grid" name="my_grid" value="<%= @grid %>">
  <input type="submit" value="Go on!">
</form>

app/views/countdown/score.html.erb
<%= @time %>

<%= @score %>

<%= link_to "Replay", game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>